"""
This file is for relational databse administration capstone project. When doing the data
engineering course on coursera there was a lot of carry over with this course.
with that i decided to complete this capstone project along with the data engineering
course/capstone to further my studies and gain more experience using the tools ive learned.
below you will find the code that i used within the project to complete the exercises/tasks.
the tools used were MySQL, Python, SQL, BashOperator.
"""

""" Data Platform Architecture and OLTP database"""
-- Create Database --
CREATE DATABASE sales;

-- Create sales_data table --
CREATE TABLE sales_data (
	product_id int NOT NULL,
    customer_id int NOT NULL,
    price int NOT NULL,
    quantity int NOT NULL,
    timestamp datetime NOT NULL
);

-- Show tables in DB -- 
SHOW TABLES -- Inputted in phpadmin, within MySQL

-- Record Count
SELECT COUNT(*) FROM `sales_data`;

-- Create index on timestamp column
CREATE INDEX ts ON sales_data (timestamp);

-- List indexes within sales_data
SHOW INDEX FROM sales_data;

-- Created a file for exporting all rows into a sql file
./datadump.sh --this is the file.

"""Build a Data Warehouse"""
"""using phpadmin to create ERD tool. below is the sql download from the tool"""
-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."softcartDimDate"
(
    dateid integer NOT NULL,
    month_num integer NOT NULL,
    month_name character varying(12) NOT NULL,
    quarter integer NOT NULL,
    week_num integer NOT NULL,
    year integer NOT NULL,
    PRIMARY KEY (dateid)
);

CREATE TABLE IF NOT EXISTS public."softcartDimCategory"
(
    categoryid integer NOT NULL,
    category character varying(20) NOT NULL,
    PRIMARY KEY (categoryid)
);

CREATE TABLE IF NOT EXISTS public."softcartDimItem"
(
    itemid integer NOT NULL,
    item character varying(100) NOT NULL,
    PRIMARY KEY (itemid)
);

CREATE TABLE IF NOT EXISTS public."softcartDimCountry"
(
    countryid integer NOT NULL,
    country character varying(30) NOT NULL,
    continent character varying(30) NOT NULL,
    PRIMARY KEY (countryid)
);

CREATE TABLE IF NOT EXISTS public."softcartFactSales"
(
    orderid integer NOT NULL,
    itemid integer NOT NULL,
    categoryid integer NOT NULL,
    countryid integer NOT NULL,
    dateid integer NOT NULL,
    price numeric(5, 2) NOT NULL,
    PRIMARY KEY (orderid)
);

ALTER TABLE IF EXISTS public."softcartFactSales"
    ADD FOREIGN KEY (itemid)
    REFERENCES public."softcartDimItem" (itemid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."softcartFactSales"
    ADD FOREIGN KEY (categoryid)
    REFERENCES public."softcartDimCategory" (categoryid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."softcartFactSales"
    ADD FOREIGN KEY (countryid)
    REFERENCES public."softcartDimCountry" (countryid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."softcartFactSales"
    ADD FOREIGN KEY (dateid)
    REFERENCES public."softcartDimDate" (dateid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;

"""once this was generated it was ran into a databse called staging to create the 
Schema, using Phpadmin for postgresSQL"""