"""Build a Data Warehouse"""
"""using phpadmin to create ERD tool. below is the sql download from the tool"""

-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."softcartDimDate"
(
    dateid integer NOT NULL,
    date date NOT NULL,
    Year integer NOT NULL,
    Quarter integer NOT NULL,
    QuarterName character(50) NOT NULL,
    Month integer NOT NULL,
    Monthname character(50) NOT NULL,
    Day integer NOT NULL,
    Weekday integer NOT NULL,
    WeekdayName character(50) NOT NULL,
    PRIMARY KEY (dateid)
);

CREATE TABLE IF NOT EXISTS public."softcartDimCategory"
(
    categoryid integer NOT NULL,
    category character varying(20) NOT NULL,
    PRIMARY KEY (categoryid)
);

CREATE TABLE IF NOT EXISTS public."softcartDimItem"
(
    itemid integer NOT NULL,
    item character varying(100) NOT NULL,
    PRIMARY KEY (itemid)
);

CREATE TABLE IF NOT EXISTS public."softcartDimCountry"
(
    countryid integer NOT NULL,
    country character varying(30) NOT NULL,
    continent character varying(30) NOT NULL,
    PRIMARY KEY (countryid)
);

CREATE TABLE IF NOT EXISTS public."softcartFactSales"
(
    orderid integer NOT NULL,
    itemid integer NOT NULL,
    categoryid integer NOT NULL,
    countryid integer NOT NULL,
    dateid integer NOT NULL,
    price numeric(5, 2) NOT NULL,
    PRIMARY KEY (orderid)
);

ALTER TABLE IF EXISTS public."softcartFactSales"
    ADD FOREIGN KEY (itemid)
    REFERENCES public."softcartDimItem" (itemid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."softcartFactSales"
    ADD FOREIGN KEY (categoryid)
    REFERENCES public."softcartDimCategory" (categoryid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."softcartFactSales"
    ADD FOREIGN KEY (countryid)
    REFERENCES public."softcartDimCountry" (countryid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."softcartFactSales"
    ADD FOREIGN KEY (dateid)
    REFERENCES public."softcartDimDate" (dateid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;

"""once this was generated it was ran into a databse called staging to create the 
Schema, using Phpadmin for postgresSQL"""

'''Following this we uploaded data into the database to be queried'''
"""The first query is a GROUPING SETS query"""
SELECT co.country, ca.category, SUM(f.amount) AS totalsales 
FROM public."FactSales" f
JOIN public."DimCountry" co
ON f.countryid = co.countryid
JOIN public."DimCategory" ca
ON f.categoryid = ca.categoryid
GROUP BY GROUPING SETS (
    (co.country, ca.category),  -- both together
    (co.country),               -- country only
    (ca.category),              -- category only
    ()                          -- grand total
) LIMIT 5;

"""Second is a ROLLUP"""
SELECT co.country, d.year, SUM(f.amount) AS totalsales 
FROM public."FactSales" f
JOIN public."DimCountry" co
ON f.countryid = co.countryid
JOIN public."DimDate" d
ON f.dateid = d.dateid
GROUP BY ROLLUP (
    co.country, d.year
) LIMIT 5;

"""Third is a Cube query"""
SELECT co.country, d.year, AVG(f.amount) AS averagesales
FROM public."FactSales" f 
JOIN public."DimCountry" co
ON f.countryid = co.countryid 
JOIN public."DimDate" d 
ON f.dateid = d.dateid 
GROUP BY CUBE ( 
    co.country, d.year 
) LIMIT 5;

"""Finally i created a materialised view called total_sales_per_country"""
CREATE MATERIALIZED VIEW total_sales_per_country (country,total_sales) AS
(SELECT 
	c.country, 
	SUM(f.amount) AS total_sales
FROM public."FactSales" f
JOIN public."DimCountry" c
	ON f.countryid = c.countryid
GROUP BY country) 